### PR TITLE
mod_post_log

### PR DESCRIPTION
**Pull request by benlangfeld**
Module for posting message logs to an HTTP API for archival outside of ejabberd.

See also #74

### CODE REVIEW

**Comment by mremond** [comment]
Thanks for sharing :)

**Comment by badlop** [comment]
It would be nice if you provide a README with some description, and maybe example usage.

**Comment by benlangfeld** [comment]
Will do. Thanks @badlop.

**Comment by mremond** [comment]
And Linux distribution ask for a License, You can add the COPYING file if this is GPLv2. That will make them happy and you get the chance to get packaged in Linux distros :)

**Comment by benlangfeld** [comment]
We'd prefer to make this MIT, if that is compatible with ejabberd, @mremond.

**Comment by mremond** [comment]
That should, as for now it is distributed separately. I think we can sort this out if we need to bundle it with ejabberd in the future.

**Pull request merged**
