### PR TITLE
mod_post_log [2.1.x]

### PR DESCRIPTION
**Pull request by benlangfeld**
Module for posting message logs to an HTTP API for archival outside of ejabberd.

### CODE REVIEW

**Comment by mremond** [comment]
Thank you ! We will have a look :)

**Comment by badlop** [comment]
Hi, I recommend you to write a README file describing the module purpose, configurable options, example configuration, and a pair of example calls. See mod_rest's README file for ideas.

**Comment by benlangfeld** [comment]
See https://github.com/processone/ejabberd-contrib/blob/master/mod_post_log/README.txt. Honestly this version (for 2.x) should be considered unmaintained. It was the original, but we since moved to new ejabberd and won't ever be going back :)

**Comment by badlop** [comment]
Ah, ok

**Pull request merged**
