### PR TITLE
add send_message_normal command

### PR DESCRIPTION
**Pull request by hamano**

### CODE REVIEW

**Comment by badlop** [comment]
With this new command, there would be three different commands just to send messages.
Maybe I should provide only one command that accepts Type as argument, like this:
```
ejabberdctl send_message normal from@localhost to@localhost some_subject some_body
```

**Comment by weiss** [comment]
> Maybe I should provide only one command that accepts Type as argument

+1

**Comment by mremond** [comment]
:+1:

**Comment by hamano** [comment]
:+1:

**Pull request merged**
